### ISSUE TITLE
Failed to connect to repository : Error performing command: git ls-remote -h git@github.com:j<my username>/game-of-life.git HEAD 

### ISSUE THREAD

**Issue by BruceAli** [wakaleo/jenkins-the-definitive-guide-book#31]
So what is this issue. Why is n't there anything mentioned about it in the book. I am using Max OSX exactly like the author. Can someone help? otherwise I have to say that I am totally disappointed buying this book. It gives you problems right from the start and things do not work properly with Git.

**Comment by pradeepe** [comment]
answer to your question please refer https://www.youtube.com/watch?v=SRAQzs41ct4

**Comment by idchlife** [comment]
I had error when git was not installed for user jenkins.

**Comment by ChrisXiuxiu** [comment]
I have the same problem too~~ and i don't know how to deal with it

**Comment by ChrisXiuxiu** [comment]
I have the same problem too~~ and i don't know how to deal with it

**Comment by idchlife** [comment]
@ChrisXiuxiu try installing git via jenkins user

**Comment by ChrisXiuxiu** [comment]
I have installed git plugins already

**Comment by wakaleo** [comment]
Jenkins needs git to be installed and configured correctly on the build server to work with git.

**Comment by am-firnas** [comment]
same issue here too, git and github plugins are preinstalled to jenkins.but I think the issue is to deal with ssh, but don't know how.
